### ISSUE TITLE
Release 2: Przetłumaczenie interfejsu użytkownika do 14.06.2017

### ISSUE THREAD

**Issue by teneusz** [teneusz/aplikacja_mobilna_komunikator#11]
Przetłumaczenie interfejsu użytkownika na jeden lub więcej nowożytnych języków
Deadline: 14.06.2017

**Comment by mras2303** [comment]
Języki:

+ Polski
+ Angielski
+ Niemiecki (jeśli starczy czasu)
+ Francuski (jeśli starczy czasu)
+ Hiszpański (jeśli starczy czasu)
