### ISSUE TITLE
Tworzenie listy kontaktów do 17.05.2017

### ISSUE THREAD

**Issue by teneusz** [teneusz/aplikacja_mobilna_komunikator#15]
- stworzenie i zaimplementowanie modułu do dodawania znajomych, i wyświetlania listy kontaktów

**Comment by adrian-kubala** [comment]
Proszę o ocenę wykonanego zadania w celu jego zamknięcia

**Comment by teneusz** [comment]
Zadanie zaakceptowane do zamnięcia

**Comment by adrian-kubala** [comment]
- możliwość wyszukiwania z listy kontaktów i spośród listy potencjalnych znajomych
