### ISSUE TITLE
Diagram przypadków użycia

### ISSUE THREAD

**Issue by teneusz** [teneusz/aplikacja_mobilna_komunikator#21]
Stworzenie diagramu przypadków użycia na podstawie dokumentacji

**Comment by Morax94** [comment]
Diagram przypadków użycia sprawdź  proszę i powiedz czy mogę go umieścić na wiki i w jakiej sekcji. [https://drive.google.com/open?id=0B4cu-5jgiiZBUlJrUHRwLTB3ZTg](url)

**Comment by mras2303** [comment]
Zmiany

1. Do wyszukiwania oraz dodawania kontaktów konieczne jest zalogowanie oraz posiadanie konta
2. Dodatkowo komunikowanie podzieliłbym na : 
a) prowadzenie rozmowy z dana osoba
b) prowadzenie konwersacji z kilkoma osobami naraz

**Comment by Morax94** [comment]
Zmiany zostały wprowadzone diagram przypadków użycia został dodany.

**Comment by Morax94** [comment]
Do poprawy:
odwrócić i zmienić strzałki między Logowaniem a Rejestracją oraz .
poprawić notacje z include i Extends na <<include>> i <<extends>>
Stworzyć scenariusz dla przypadku użycia Logowanie.

**Comment by Morax94** [comment]
Poprawiony diagram przypadków użycia:
https://drive.google.com/open?id=0B4cu-5jgiiZBUlJrUHRwLTB3ZTg

**Comment by mras2303** [comment]
Popraw tą literówkę przy rejestracji

**Comment by Morax94** [comment]
Literówka poprawiona link jak wyżej.

**Comment by Morax94** [comment]
Diagram poprawiony
