### ISSUE TITLE
UI - rejestracja użytkownika

### ISSUE THREAD

**Issue by teneusz** [teneusz/aplikacja_mobilna_komunikator#22]
- Stworzenie modelu rejestracji użytkownika
- Stworzenie pliku xml z funkjonalnościa modelu
- Wystylizowanie pliku xml

**Comment by Morax94** [comment]
Proszę o sprawdzenie modelu rejestracji i akceptacje. https://app.moqups.com/potaczek2626@gmail.com/K38Yy65uq1/view/page/a330386a4
