### ISSUE TITLE
UI - Wygląd szczegółów użytkownika

### ISSUE THREAD

**Issue by teneusz** [teneusz/aplikacja_mobilna_komunikator#23]
- Stworzenie modelu szczegółów użytkownika
- Stworzenie pliku xml z funkjonalnościa modelu
- Wystylizowanie pliku xml

**Comment by Morax94** [comment]
Proszę o akceptacje modelu https://app.moqups.com/potaczek2626@gmail.com/K38Yy65uq1/view/page/ae6be6009
