### ISSUE TITLE
Stworzenie logo

### ISSUE THREAD

**Issue by mras2303** [teneusz/aplikacja_mobilna_komunikator#24]

**Comment by adrian-kubala** [comment]
![gderacz-v1](https://cloud.githubusercontent.com/assets/22918451/24083364/16833236-0cd6-11e7-9078-e7602e677df2.png)
![gderacz-v2](https://cloud.githubusercontent.com/assets/22918451/24083365/16b2fb10-0cd6-11e7-90f7-cf1587a6f5bd.png)

**Comment by mras2303** [comment]
Numer 2 lepszy według mnie

**Comment by adrian-kubala** [comment]
Mała modyfikacja odnośnie drugiej propozycji: 
![gderacz-v2-1](https://cloud.githubusercontent.com/assets/22918451/24083524/a61ea4e6-0cd8-11e7-873a-dba827de804b.png)
