### ISSUE TITLE
UI - przygotowanie wyglądu aktywności logowania

### ISSUE THREAD

**Issue by teneusz** [teneusz/aplikacja_mobilna_komunikator#3]
Stworzenie wyglądu okna logowania

**Comment by Morax94** [comment]
Czy akceptujesz wygląd okna logowania?
https://app.moqups.com/potaczek2626@gmail.com/K38Yy65uq1/view/page/a0e3aef25

**Comment by teneusz** [comment]
Jestem na tak

**Comment by adrian-kubala** [comment]
Proszę o akceptację utworzonego layoutu.
