### ISSUE TITLE
Stworzenie modułu logowania i rejestracji.

### ISSUE THREAD

**Issue by Morax94** [teneusz/aplikacja_mobilna_komunikator#31]
- wybranie konkretnej metody szyfrowania hasła oraz przesyłu danych do bazy danych,
- zaimplementowanie metody sprawdzania poprawności hasła,
- zaimplementowanie metody zabezpieczenia przed nieuprawnionym dostępem (np. blokowanie konta po trzykrotnym błędnym wpisaniu hasła.

**Comment by teneusz** [comment]
Merged with develop
