### ISSUE TITLE
Brak możliwości zarejestrowania nowego użytkownika.

### ISSUE THREAD

**Issue by Morax94** [teneusz/aplikacja_mobilna_komunikator#36]
Przy rejestracji wyświetla się komunikat "Coś poszło nie tak" w Android monitor występują w błędy w StartActivity.

**Comment by teneusz** [comment]
Rejestracja poprawiona. Proszę o sprawdzenie czy błąd dalej występiuje

**Comment by adrian-kubala** [comment]
Rejestracja działa. Zamykam.
