### ISSUE TITLE
UI - wygląd konwersacji / rozmów

### ISSUE THREAD

**Issue by teneusz** [teneusz/aplikacja_mobilna_komunikator#6]
Stworzenie wyglądu konwersacji / rozmowy

**Comment by Morax94** [comment]
Proszę o akceptacje wyglądu aktywności.
https://app.moqups.com/potaczek2626@gmail.com/K38Yy65uq1/view/page/a77955efe

**Comment by adrian-kubala** [comment]
Ukończono widok i szablony klas dla aktywności, jednak bez menu rozwijalnego.
