### ISSUE TITLE
UI - wygląd wyszukiwarki użytkowników

### ISSUE THREAD

**Issue by teneusz** [teneusz/aplikacja_mobilna_komunikator#7]
Stworzenie wyglądu wyszukiwarki użytkowników

**Comment by mras2303** [comment]
Szczegóły wyszukiwania:
1. Jedno pole do wprowadzania danych działające w trybie real-time (bez klikania w button) wyszukujące po username/email
2. Przycisk wyszukujący ludzi zarejestrowanych w pobliżu naszej lokalizacji

**Comment by Morax94** [comment]
Proszę o uwagi do wyglądu https://app.moqups.com/potaczek2626@gmail.com/K38Yy65uq1/view/page/a267370ee

**Comment by adrian-kubala** [comment]
Ukończono layouty dla komórek tabeli. Sekcje zostaną obsłużone za pomocą [tego rozwiązania.](https://gist.github.com/gabrielemariotti/4c189fb1124df4556058)
