### ISSUE TITLE
UI - wygląd ustawień

### ISSUE THREAD

**Issue by teneusz** [teneusz/aplikacja_mobilna_komunikator#8]
Stworzenie wyglądu okna ustawień

**Comment by mras2303** [comment]
Zawartość ustawień:
1. Dźwięki ON/OFF
2. Powiadomienia ON/OFF
3. Zgoda na śledzenie lokalizacji ON/OFF
4. Zgoda na zapraszanie do znajomych ON/OFF
5. Przechowywanie archiwum ON/OFF
6. Usunięcie archiwum
7. Upload zdjęcia profilowego

**Comment by Morax94** [comment]
Przykładowy wygląd niektórych opcji, Coś poprawić? 
https://app.moqups.com/potaczek2626@gmail.com/K38Yy65uq1/view/page/a5d862c05

**Comment by Morax94** [comment]
Na moqups znajdują się tylko przykładowe opcje. Pełną zawartość ustawień sam (@mras2303 ) wypisałeś.
